TAF_IDENTIFIER = "name"

TAF_NODE="node"
TAF_NODE_NB_INSTANCES ="nb_instances"
TAF_NODE_MIN = "min"
TAF_NODE_MAX = "max"

TAF_PARAMETER = "parameter"
TAF_PARAMETER_CATEGORY = "category"
TAF_PARAMETER_TYPE = "type"
TAF_PARAMETER_MIN = "min"
TAF_PARAMETER_MAX ="max"
TAF_PARAMETER_VALUES = "values"
TAF_PARAMETER_WEIGHTS = "weigths"
TAF_PARAMETER_DISTRIBUTION = "distribution"
TAF_PARAMETER_VARIANCE = "variance"
TAF_PARAMATER_MEAN = "mean"
TAF_PARAMETER_RANGES = "ranges"
TAF_PARAMETER_NAME = "name"

TAF_CONSTRAINT = "constraint"
TAF_CONSTRAINT_TYPE = "types"
TAF_CONSTRAINT_EXPRESSIONS= "expressions"
TAF_CONSTRAINT_QUANTIFIERS= "quantifiers"
TAF_CONSTRAINT_RANGES="ranges"

TAF_TYPE = "type"

TAF_REFERENCE = "reference"
TAF_REFERENCED_NODE ="ref"
TAF_REFERENCE_DEPTH ="depth"
TAF_REFERENCE_MAX_DEPTH ="max_depth"
TAF_REFERENCE_MIN_DEPTH="min_depth"
TAF_REFERENCE_BRANCHING="nb_instances"
TAF_REFERENCE_MAX_BRANCHING="max"

TAF_KEYS = {TAF_PARAMETER_CATEGORY, TAF_PARAMETER_TYPE, TAF_PARAMETER_VALUES, TAF_PARAMETER_MAX, TAF_PARAMETER_MIN, TAF_PARAMETER_NAME,TAF_PARAMETER_WEIGHTS, TAF_PARAMETER_DISTRIBUTION, TAF_PARAMETER_VARIANCE, TAF_PARAMATER_MEAN,TAF_PARAMETER_RANGES}

TAF_PARAMETERS_ATTRIBS = {TAF_PARAMETER,TAF_PARAMETER_TYPE}
TAF_CONSTRAINTS_ATTRIBS = {TAF_CONSTRAINT,TAF_CONSTRAINT_TYPE}
TAF_NODES_ATTRIBS = {TAF_NODE_NB_INSTANCES}
TAF_ATTRIB = "category"